name: build
on: [push, pull_request]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: test
        working-directory: ./test
        run: npm run start

      - name: migrate
        working-directory: ./packages/migrate
        run: npm install && npm run build && npm run test